use glfw::Key::*;
use crate::points::Point;

pub fn key_to_point(key: glfw::Key) -> Option<Point> {
    match key {
        Escape =>  Some(Point(-5, -3)),
        F1 =>  Some(Point(-4, -3)),
        F2 =>  Some(Point(-3, -3)),
        F3 =>  Some(Point(-2, -3)),
        F4 =>  Some(Point(-1, -3)),
        F5 =>  Some(Point(0, -3)),
        F6 =>  Some(Point(1, -3)),
        F7 =>  Some(Point(2, -3)),
        F8 =>  Some(Point(3, -3)),
        F9 =>  Some(Point(4, -3)),
        F10 =>  Some(Point(5, -3)),
        F11 =>  Some(Point(6, -3)),
        F12 =>  Some(Point(7, -3)),
        Delete =>  Some(Point(8, -3)),

        GraveAccent  =>  Some(Point(-6, -2)),
        Num1  =>  Some(Point(-5, -2)),
        Num2  =>  Some(Point(-4, -2)),
        Num3  =>  Some(Point(-3, -2)),
        Num4  =>  Some(Point(-2, -2)),
        Num5  =>  Some(Point(-1, -2)),
        Num6  =>  Some(Point(0, -2)),
        Num7  =>  Some(Point(1, -2)),
        Num8  =>  Some(Point(2, -2)),
        Num9  =>  Some(Point(3, -2)),
        Num0  =>  Some(Point(4, -2)),
        Minus  =>  Some(Point(5, -2)),
        Equal  =>  Some(Point(6, -2)),
        Backspace  =>  Some(Point(7, -2)),

        Tab  =>  Some(Point(-6, -1)),
        Q  =>  Some(Point(-5, -1)),
        W  =>  Some(Point(-4, -1)),
        E  =>  Some(Point(-3, -1)),
        R  =>  Some(Point(-2, -1)),
        T  =>  Some(Point(-1, -1)),
        Y  =>  Some(Point(0, -1)),
        U  =>  Some(Point(1, -1)),
        I  =>  Some(Point(2, -1)),
        O  =>  Some(Point(3, -1)),
        P  =>  Some(Point(4, -1)),
        LeftBracket  =>  Some(Point(5, -1)),
        RightBracket  =>  Some(Point(6, -1)),
        Backslash =>  Some(Point(7, -1)),

        CapsLock  =>  Some(Point(-6, 0)),
        A  =>  Some(Point(-5, 0)),
        S  =>  Some(Point(-4, 0)),
        D  =>  Some(Point(-3, 0)),
        F  =>  Some(Point(-2, 0)),
        G  =>  Some(Point(-1, 0)),
        H  =>  Some(Point(0, 0)),
        J  =>  Some(Point(1, 0)),
        K  =>  Some(Point(2, 0)),
        L  =>  Some(Point(3, 0)),
        Semicolon  =>  Some(Point(4, 0)),
        Apostrophe  =>  Some(Point(5, 0)),
        Enter  =>  Some(Point(6, 0)),

        LeftShift =>  Some(Point(-6, 1)),
        Z  =>  Some(Point(-5, 1)),
        X  =>  Some(Point(-4, 1)),
        C  =>  Some(Point(-3, 1)),
        V  =>  Some(Point(-2, 1)),
        B  =>  Some(Point(-1, 1)),
        N  =>  Some(Point(0, 1)),
        M  =>  Some(Point(1, 1)),
        Comma  =>  Some(Point(2, 1)),
        Period  =>  Some(Point(3, 1)),
        Slash  =>  Some(Point(4, 1)),
        RightShift  =>  Some(Point(5, 1)),
        Up =>  Some(Point(6, 1)),

        LeftControl =>  Some(Point(-7, 2)),
        LeftAlt =>  Some(Point(-6, 2)),
        LeftSuper =>  Some(Point(-5, 2)),
        Menu =>  Some(Point(1, 2)),
        RightAlt =>  Some(Point(2, 2)),
        RightControl =>  Some(Point(3, 2)),
        Left =>  Some(Point(4, 2)),
        Down =>  Some(Point(5, 2)),
        Right =>  Some(Point(6, 2)),
        _ => None,
    }
}
